### ISSUE TITLE
Unable to edit site content via Paneron/Aperis

### ISSUE THREAD

**Issue by ronaldtse** [expresslang/ap210.org#1]
Ping @strogonoff .

**Comment by ronaldtse** [comment]
@strogonoff @TRThurman is waiting for this.

**Comment by strogonoff** [comment]
On it.

**Comment by strogonoff** [comment]
Apologies for delay. New version of Aperis was released Monday; it (1) is functional for editing static doc pages and (2) uses an updated site/data structure that accommodates news roll (a blog-like timeline).

Two outstanding items are: (A) migrate this repository to the new data structure (ETA today), (B) finish & enable UI related to post drafting & publishing and (C) update site deployment routine to accommodate new structure.

**Comment by strogonoff** [comment]
Hi @TRThurman! This is Anton, I’m working on Paneron host application and Aperis open project site editor GUI extension for Paneron. Should we schedule a chat/walkthrough on how to edit ap210.org start to end? I’m thinking a 30-minute call with screensharing. Could do this Friday or the next convenient for you day.

(cc @ronaldtse)

**Comment by TRThurman** [comment]
Hi 
That would be wonderful.
If we could also record the session, that would be even better.
Then I could better remember the process and share with a couple other folks I want to permit to add content.

How about 9AM Mountain Time Friday?

Tom

**Comment by strogonoff** [comment]
Time works for me, accepted event invite!
