### ISSUE TITLE
Set up a site using Open Project framework

### ISSUE THREAD

**Issue by strogonoff** [expresslang/ap210.org#11]
While Aperis build is being sorted out, we can have an Open Project site working and then migrate content in a semi-automatic way.

**Comment by strogonoff** [comment]
Site is almost ready to go. There is actually some content to migrate to AsciiDoc in the `main` branch, I was looking at the old `master` branch and thought there’s no content.

**Comment by strogonoff** [comment]
I see the current contents in the `main` branch are mostly static files, that should be made available for site visitors for download. I’ll try to create a simple automatic HTML listing of those files before deploying the site.

**Comment by TRThurman** [comment]
Hi Anton 
Will that automation work as we add more files?
Thomas

**Comment by strogonoff** [comment]
> Will that automation work as we add more files?

Yes. Basically, any files added under the new `/deliverables/` directory will be listed in the [tree-like browser](https://www.ap210.org/docs/section-1/deliverables/) after the next push.

However, with many more thousands the speed will degrade. I suggest that we review how file browser should work, and the exact use scenarios site visitors have for it…

**Comment by strogonoff** [comment]
I think this particular issue is done, the site is live, further improvements will be tracked separately.
