### ISSUE TITLE
Dataset browser may not be very useful

### ISSUE THREAD

**Issue by strogonoff** [expresslang/ap210.org#13]
Currently, it allows to search for and download individual files. I imagine site visitors won’t typically use it this way. Perhaps they would like some means to download related data as they make their way through other documentation, or something else. Before committing to improvements on the dataset browser, it would help to discuss the use scenarios and patterns for dataset access by site visitors.

**Comment by TRThurman** [comment]
I agree.
We (Anne and I) need to put some high level content in place.
This is a great start!

**Comment by ronaldtse** [comment]
I have split up the pages to implement the site structure (#15) so I've disabled the dataset browser for now. Closing.
