### ISSUE TITLE
Dataset browser performance: do not provide full dataset index in an inline script

### ISSUE THREAD

**Issue by strogonoff** [expresslang/ap210.org#14]
The plan is:

1. At build time, generate JSON files with dataset index and corresponding hash (possibly separate for each dataset)
2. When website is visited and a dataset is browsed, fetch the index and cache it on user’s computer along with the hash
3. Upon subsequent visits, when loading a dataset, compare remote and cached hashes; if they differ then do (2) again, otherwise initialize dataset browser with locally stored index

This means:

- Page will load much faster, since dataset index doesn’t need to be loaded unless user interacts with dataset browser
- Dataset loads after the first one will be much faster since data does not need to be fetched every time
- Separating multiple indexes will reduce initial dataset load time (but there may be a short loading wait before opening another dataset)

**Comment by TRThurman** [comment]
A new site structure is being implemented. Impact on performance tbd.

**Comment by ronaldtse** [comment]
Not using dataset browser right now. Closing.
