### ISSUE TITLE
documentation pages get a 404 error

### ISSUE THREAD

**Issue by TRThurman** [expresslang/ap210.org#19]
Anton, Brandon,
Can you provide some guidance here?

Not sure how long this has been a problem but I am getting a 404 error when trying to go to /docs etc.,

Thanks!
Tom

**Comment by TRThurman** [comment]
I noticed on my local repo I have an index.markdown. could that be a culprit?
Compressed to get around github quarantine of markdown extension.
[index.markdown.zip](https://github.com/expresslang/ap210.org/files/8840899/index.markdown.zip)

**Comment by ronaldtse** [comment]
This is fixed now. Closing.
