### ISSUE TITLE
Move ap210.org to GitHub Pages

### ISSUE THREAD

**Issue by ronaldtse** [expresslang/ap210.org#23]
For @kwkwan . Also delete AWS infrastructure since it's not needed right now.

**Comment by kwkwan** [comment]
Hi @ronaldtse, please grrant me as admin because I cannot access the Setting page.  Thanks!

**Comment by ronaldtse** [comment]
@kwkwan done, thanks!

**Comment by ronaldtse** [comment]
@kwkwan actually we cannot use ap210.github.io because that is the "organization page" only intended for a GitHub Organization. We can use any name for this repository, ap210.org is fine.

**Comment by kwkwan** [comment]
I will change it back to ap210.org

**Comment by kwkwan** [comment]
@ronaldtse For setting up custom domain, Github page only support <organization>.github.io or <user>.github.io.  We may need to move `ap210.org` under organization `ap210`.

**Comment by ronaldtse** [comment]
It is not well described, but GitHub does support "project sites" (`xxx.github.io/reponame`) in custom domains as (`https://example.com`), with the DNS record of `example.com` pointing to `xxx.github.io`.

I've already changed the DNS settings, and it works:
https://www.ap210.org

<img width="1072" alt="Screenshot 2023-08-15 at 10 43 12 AM" src="https://github.com/expresslang/ap210.org/assets/11865/0935826a-08a8-4046-a615-c92cb398fe5b">

**Comment by ronaldtse** [comment]
Confirm completed.
