### ISSUE TITLE
document source format is unexpected.

### ISSUE THREAD

**Issue by TRThurman** [expresslang/ap210.org#3]
After installing paneron, getting the site loaded, and the aperis plugin, i selected the landing page to edit.
this is what I see
I assume something is amuck as I didn't expect to be editing code.
:

Ouch! This document could not be loaded. Most likely the structure does not conform to the ProseMirror schema expected by this editor instance (such as by using content blocks that the schema does not have provisions for), or source data could be malformed in some other way.
...
Below you can correct the source document so that it uses a structure that conforms to required schema.

"root":{2 items
"type":string"doc"
"content":[2 items
0:{3 items
"type":string"section"
"attrs":{1 item
"id":string"what-is-ap210"
}
"content":[2 items
0:{2 items
"type":string"section_header"
"content":[1 item
0:{2 items
"type":string"text"
"text":string"What is ap210?"
}
]
}
1:{2 items
"type":string"paragraph"
"content":[1 item
0:{2 items
"type":string"text"
"text":string"AP 210 is a standard from ISO/TC 184/SC 4."
}
]
}
]
}
1:{3 items
"type":string"section"
"attrs":{1 item
"id":string"abstract"
}
"content":[8 items
0:{2 items
"type":string"section_header"
"content":[1 item
0:{2 items
"type":string"text"
"text":string"Abstract"
}
]
}
1:{2 items
"type":string"bullet_list"
"content":[1 item
0:{2 items
"type":string"list_item"
"content":[1 item
0:{2 items
"type":string"paragraph"
"content":[1 item
0:{2 items
"type":string"text"
"text":string"Abstract."
}
]
}
]
}
]
}
2:{2 items
"type":string"paragraph"
"content":[1 item
0:{2 items
"type":string"text"
"text":string"Link to concept of operations"
}
]
}
3:{2 items
"type":string"paragraph"
"content":[1 item
0:{2 items
"type":string"text"
"text":string"Link to https://www.ap242.org"
}
]
}
4:{2 items
"type":string"paragraph"
"content":[1 item
0:{2 items
"type":string"text"
"text":string"Link to ISO"
}
]
}
5:{2 items
"type":string"paragraph"
"content":[1 item
0:{2 items
"type":string"text"
"text":string"Training details"
}
]
}
6:{2 items
"type":string"paragraph"
"content":[1 item
0:{2 items
"type":string"text"
"text":string"link to recommended practice docs"
}
]
}
7:{2 items
"type":string"paragraph"
"content":[1 item
0:{2 items
"type":string"text"
"text":string"AP 210 related research"
}
]
}
]
}
]
}
Following errors were encountered while validating the document:

RangeError: Unknown node type: section_header

**Comment by strogonoff** [comment]
This has been fixed, apologies.
