### ISSUE TITLE
upload data sets

### ISSUE THREAD

**Issue by TRThurman** [expresslang/ap210.org#8]
Uploading sample data generated by AP 210 related research.

**Comment by TRThurman** [comment]
NIST SPICE DATA added.

**Comment by TRThurman** [comment]
Now includes some IDF tp AP 210 data

**Comment by TRThurman** [comment]
NIST javadoc data and code added.

**Comment by TRThurman** [comment]
Initial upload complete.
There are some issues with the ap210Testcases directories 
-- (missing content from github large file upload tool?)
-- duplicates

**Comment by strogonoff** [comment]
Data sets are made available via a simple tree-like file browser (a custom JavaScript widget) at https://www.ap210.org/docs/section-1/deliverables/. This path will likely change as site structure is more clear… Any further deliverables can be added under the https://github.com/expresslang/ap210.org/tree/main/deliverables directory. (It is expected that they’ll be grouped in folders as before.)

**Comment by ronaldtse** [comment]
I've moved most of the uploaded data to new repositories. There are some duplication in content that needs to be resolved, for example, duplicated JavaDocs for JSDAI.
